package consts;

public enum BossType {
    ANTROM,
    YARDART,
    FINAL,
    SKILLSUMMONED,
    BROLY,
    PLAYERAO,
    PHOBAN,
    PHOBANDT,
    PHOBANBDKB,
    PHOBANCDRD,
    PHOBANKGHD,
    TRUNGTHU_EVENT,
    HALLOWEEN_EVENT,
    CHRISTMAS_EVENT,
    HUNGVUONG_EVENT,
    TET_EVENT,
    MANAGER_DEBUG
}
